### ISSUE TITLE
Add enumerated PMID option for RAS Machine

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#294]
I have a list of PubMed identifiers I'd explicitly like my instance of the RAS machine to read. I had the idea to add another element to `config.yaml` that looks like this:

```yaml
belief_threshold: 0.8

search_terms:
- "Microglia"
- "Amyloid Beta"

search_genes:
- "TREM2"
- "CD33"

enumerated_pmids:
- "10869359"
- "27478040"
```

From how I understand it, the `pmids` dictionary gets filled up with keys for various search terms and genes, then the values are lists of PubMed identifiers. I added the following lines to `rasmachine.py` before the model is extended:

```python
enumerated_pmids = config.get('enumerated_pmids')
if enumerated_pmids:
    pmids['enumerated_pmids'] = list(enumerated_pmids)
    logger.info('Using %d enumerated PubMed identifiers', len(enumerated_pmids))
else:
    logger.info('No PubMed identifiers were enumerated')
```

I haven't made a PR for this because I'm not sure if it fits in with the way you see this tool being used. Also, it doesn't work so I was hoping for a bit of advice :)
